"""election language

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 13:44:33.648629
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('language', sa.String(), server_default='de', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'language')
    # ### end Alembic commands ###
