"""invitations dispatched

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 17:06:47.554833
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('invitations_dispatched', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'invitations_dispatched')
    # ### end Alembic commands ###
