"""verification request

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 18:46:08.722836
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_website', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('verification_requested_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('verification_token_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_organizations_verification_token_hash'), 'organizations', ['verification_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_verification_token_hash'), table_name='organizations')
    op.drop_column('organizations', 'verification_token_hash')
    op.drop_column('organizations', 'verification_requested_at')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'contact_website')
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'contact_name')
    # ### end Alembic commands ###
