"""confirmed accounts and send tracking

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 19:45:42.837498
"""
import secrets

from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('send_queued_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    conn = op.get_bind()
    # Bestehende Konten gelten als bestätigt (sonst würden sie als "nie bestätigt" gelöscht)
    conn.execute(sa.text("UPDATE organizations SET confirmed_at = created_at WHERE confirmed_at IS NULL"))

    # Bestehende Stimmen/Einladungen einmal in zufälliger Reihenfolge neu schreiben:
    # löst die xmin/ctid-Korrelation aus der Zeit vor scramble_row_versions() auf.
    rows = [("votes", "choice", r[0]) for r in conn.execute(sa.text("SELECT id FROM votes"))]
    rows += [("invitations", "used", r[0]) for r in conn.execute(sa.text("SELECT id FROM invitations"))]
    secrets.SystemRandom().shuffle(rows)
    for table, column, row_id in rows:
        conn.execute(sa.text(f"UPDATE {table} SET {column} = {column} WHERE id = :id"), {"id": row_id})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'confirmed_at')
    op.drop_column('invitations', 'send_queued_at')
    # ### end Alembic commands ###
