"""admin portal

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-04 12:53:09.115109
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mail_paused', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.add_column('magic_links', sa.Column('admin', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('magic_links', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('organizations', sa.Column('blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('max_recipients', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_recipients')
    op.drop_column('organizations', 'last_active_at')
    op.drop_column('organizations', 'blocked')
    op.alter_column('magic_links', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('magic_links', 'admin')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admin_state')
    # ### end Alembic commands ###
