"""admin identity

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-04 13:31:19.558116
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_state', sa.Column('admin_email_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_state', 'admin_email_hash')
    # ### end Alembic commands ###
